version: "3.2"

services:

  db_gobarber:
    container_name: db_gobarber
    image: postgres
    environment:
      POSTGRES_DB: 'gostack_desafio06'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    #volumes:
      #- ./database/docker-data/postgres:/var/lib/postgresql/data
      #- ./database/:/docker-entrypoint-initdb.d/
    networks:
      - network-gobarber

  db_gobarber_tests:
    container_name: db_gobarber_tests
    image: postgres
    environment:
      POSTGRES_DB: 'gostack_desafio06_tests'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - "5433:5432"
    expose:
      - "5432"

networks:
  network-gobarber:
    driver: bridge

